server:
  port: 8085
spring:
  application:
    name: ca-api
  datasource:
    url: jdbc:postgresql://localhost:5432/caevents
    username: causer
    password: capass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30s
