server:
  port: 8084
spring:
  application:
    name: ca-materializer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ca-materializer-group
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://localhost:5432/caevents
    username: causer
    password: capass
  jpa:
    hibernate:
      ddl-auto: update
