server:
  port: 8084

spring:
  application:
    name: ca-materializer
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${CA_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ca-materializer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.gagroup.ca.model
  datasource:
    url: ${CA_DB_URL}
    username: ${CA_DB_USERNAME}
    password: ${CA_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
